YOUTUBE_API_PLAYLIST_URL="https://www.googleapis.com/youtube/v3/playlistItems"
YOUTUBE_API_VIDEO_URL="https://www.googleapis.com/youtube/v3/videos"
# PLAYLIST_ID = "PL1v8zpldgH3rJk6UKP_npByDuE7v1WSdt"
PLAYLIST_ID = "PLQVvvaa0QuDfp4GmCdhbPhPwWt4O_TBmB"
KAFKA_TOPIC = "youtube-videos"
GROUP_ID = "watcher_group"
BOOTSTRAP_SERVERS = "localhost:29092"
